/**
 * 监控对象
 */
CREATE TABLE monitor_object(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
	app_id BIGINT(20) NOT NULL COMMENT '应用ID',
	type INT(3) NOT NULL COMMENT '类型',
	target VARCHAR(256) NOT NULL COMMENT '目标',
	frequency INT(11) DEFAULT NULL COMMENT '频率',
	remark VARCHAR(256) DEFAULT NULL COMMENT '备注',
	status TINYINT(1) NOT NULL COMMENT '状态,1:启用,2:停用,3:删除',
	creator VARCHAR(64) NOT NULL COMMENT '创建者',
	created DATETIME NOT NULL COMMENT '创建时间',
	modifier VARCHAR(64) NOT NULL COMMENT '修改者',
	modified DATETIME NOT NULL COMMENT '修改时间'
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '监控对象';
/** 添加索引、约束等*/

/**
 * 监控结果
 */
CREATE TABLE monitor_result(
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
	app_id BIGINT(20) NOT NULL COMMENT '应用ID',
	monitor_object_id BIGINT(20) NOT NULL COMMENT '监控对象ID',
	monitor_type TINYINT(2) NOT NULL COMMENT '监控类型',
	code TINYINT(1) NOT NULL COMMENT '编码',
	content VARCHAR(4096) NOT NULL COMMENT '内容',
	remark VARCHAR(256) DEFAULT NULL COMMENT '备注',
	status TINYINT(1) NOT NULL COMMENT '状态,1:启用,2:停用,3:删除',
	creator VARCHAR(64) NOT NULL COMMENT '创建者',
	created DATETIME NOT NULL COMMENT '创建时间',
	modifier VARCHAR(64) NOT NULL COMMENT '修改者',
	modified DATETIME NOT NULL COMMENT '修改时间'
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT '监控结果';
